
export const project = [
  {
    id: "project1",
    name: "Break Bricks",
    img: "assets/BreakBricks.gif",
    githubLink: "https://github.com/505539367/Break-Bricks",
    demoLink: "https://505539367.github.io/Break-Bricks/",
    date: "Aug 2022",
  },
  {
    id: "project2",
    name: "FoodGram",
    img: "assets/FoodGram.gif",
    githubLink: "https://github.com/505539367/Fever-Tourism",
    demoLink: "https://www.youtube.com/watch?v=tI271LDUpLU",
    date: "Nov 2021 - Dec 2021",
  },
  {
    id: "project3",
    name: "Fever Tourism",
    img: "assets/FeverTourism.png",
    githubLink: "https://github.com/505539367/Fever-Tourism",
    demoLink: "https://jovial-raindrop-fa762f.netlify.app/",
    date: "March 2022 - May 2022",
  },
  {
    id: "project4",
    name: "GradSchoolZero",
    img: "assets/GradSchoolZero.jpeg",
    githubLink: "https://github.com/505539367/graduate_system",
    demoLink: "",
    date: "Oct 2021 - Dec 2021",
  },
  {
    id: "project5",
    name: "Instagram Clone",
    img: "assets/InstagramClone.gif",
    githubLink: "https://github.com/505539367/InstagramClone",
    demoLink: "https://github.com/505539367/InstagramClone/blob/master/walkthrough2.gif",
    date: "Oct 2021",
  },
  {
    id: "project6",
    name: "Simple Tweet",
    img: "assets/SimpleTweet.gif",
    githubLink: "https://github.com/505539367/SimpleTweet",
    demoLink: "https://raw.githubusercontent.com/505539367/SimpleTweet/master/walkthrough2.gif",
    date: "Oct 2021",
  },
  {
    id: "project7",
    name: "Flixster",
    img: "assets/Flixster.gif",
    githubLink: "https://github.com/505539367/Flixster",
    demoLink: "https://github.com/505539367/Flixster/blob/master/walkthrough2.gif",
    date: "Sep 2021",
  },
]